### ISSUE TITLE
ouptut_app hooks are not working

### ISSUE THREAD

**Issue by r0hi7** [tnich/honssh#110]
I added the script that is to be called when download begins also enbaled app hooks. But the app hooks are not working! Any
Also when we enable app_hooks then we have to write something in all of them. I cant let ir run with one single script.

**Comment by tnich** [comment]
Hi @r0hi7,

Please provide more information such as the relevant configuration section and any logs relating to APP-HOOKS in the honssh.log.

**Comment by bang-uin** [comment]
Closing. Reopen if more information is provided.
