### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mboelen** [tnich/honssh#111]
We are reviewing your project to include it on our website: https://linuxsecurity.expert/tools/honssh/

During the review we could not find a license. Under what license is HonSSH available?

**Comment by robputt796** [comment]
I vote GPL or Apache2.0 @tnich, any thoughts?

**Comment by tnich** [comment]
Hi,

Sorry for the slow reply. It's published under the same license that Kippo uses. Details can be found at the top of all code files. e.g. https://github.com/tnich/honssh/blob/master/honssh.tac

**Comment by mboelen** [comment]
Thanks @tnich 

If you state it uses the Kippo license, then I guess the full copyright file needs to be used, including the name of Upi Tamminen? Link: https://github.com/desaster/kippo/blob/master/doc/COPYRIGHT

My intention is not to nitpick here, but to gain the clarity for all users, so they can actually use your tool without any conflicts. My tip would be to clone the COPYRIGHT file from the Kippo project, then state HonSSH is based upon the work of Kippo, with an additional copyright line for yourself referring to the additional work you have done. I'm not a legal expert, but that adheres to the request of Kippo project license while including your ownership as well.

What do you think?

**Comment by tnich** [comment]
Thank you for your comments @mboelen.

Any of Upi's code remains with his copyright:
https://github.com/tnich/honssh/blob/master/kippo/core/ttylog.py
Also, the readme specifies, "Parts of this project are using the kippo code and their copyright still remains with Upi Tamminen."

The rest of the code was written by myself and the copyright information at the top of each file reflects this.

**Comment by lnslbrty** [comment]
Could you please add your copyright information to this repository?
Otherwise, most companies or other developers who "Respect the Rights of Others" won't be able to reuse your code.

**Comment by robputt796** [comment]
Copyright information has been added to this repo in the COPYRIGHT file, the license seems Apache 2.0 like but it has been modified by Upi inside of Kippo which this project is based upon, I requested clarification from Upi if we can formally license Kippo under a common open source license e.g. GPL or Apache 2.0 or MIT or whatever, once he makes a choice about license we can change the verbiage around the HonSSH license as fits.

- https://github.com/desaster/kippo/issues/229

**Comment by robputt796** [comment]
Received reply, desaster (Upi) from Kippo and he confirmed this is the 3 Clause BSD license - https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_(%22BSD_License_2.0%22,_%22Revised_BSD_License%22,_%22New_BSD_License%22,_or_%22Modified_BSD_License%22) we should tag the repo as appropriate.

**Comment by robputt796** [comment]
See https://github.com/tnich/honssh/pull/115 for tagging the repo as BSD licensed :-)

**Comment by mboelen** [comment]
Thanks, we will update the project on our side as well :)
