### ISSUE TITLE
Can't Connect to Honssh but it still logs

### ISSUE THREAD

**Issue by jcbeaub** [tnich/honssh#112]
So I am working on a project for a college course that requires the use of the dockpot honeypot (I need to connect to it and I don't care if anyone else can or not) which is essentially just honssh. After having spent 8 hours trying to get honssh fully working I am at a loss, I have gotten to the point where I can start up my ssh_server on docker and then upon starting dockpot (it says it has start up properly and I start up the container it creates) and upon connecting directly to my ssh_server on docker honssh logs the connection but I am unable to actually connect to honssh. Any IP address and port I assign honssh to either has no connection or has a password I am unable to guess.

So I was wondering if anyone had a suggestion on setting up the honssh.cfg file properly so I can connect to honssh.

**Comment by bang-uin** [comment]
Hi,

please attach the log file and config file so we can have a lock at it.

**Comment by jcbeaub** [comment]
[honssh.log](https://github.com/tnich/honssh/files/1753167/honssh.log)

For the ssh addr and the client addr I have tried many addresses but none have worked so far.
#
# HonSSH configuration file (honssh.cfg)
#

#----------------------------------------------#
#                 GENERAL SETUP                #
#----------------------------------------------#

#-----------------------#
#       HONEYPOT        #
#-----------------------#
[honeypot]

# This name will be used when logging to any of the output mechanisms.
# Please ensure it is meaningful.
#
# input: Text
# required: YES
sensor_name = Dockpot

# IP addresses to listen for incoming SSH connections.
#
# input: Ip Address
# required: YES
ssh_addr = 172.16.0.2

# Port to listen for incoming SSH connections.
#
# input: Number
# required: YES
# default: 2222
ssh_port = 2222

# IP addresses to send outgoing SSH connections.
#
# input: IP Address
# required: YES
client_addr = 172.16.0.1

# IP addresses of the honeypot.
#
# input: IP ADDRESSS
# required: YES
honey_addr = 172.17.0.1 


honey_port= 32768

# Public and private SSH key files. 
#
# input: Text
# required: YES
# default: id_rsa.pub
# default: id_rsa
public_key = id_rsa.pub
private_key =id_rsa

#-----------------------#
# HONEYPOT RESTRICTIONS #
#-----------------------#
[hp-restrict]

# When enabled, HonSSH will restirct connections to password only and decline any public keys.
# HonSSH will not work with public keys - this should always be true.
#
# input: true/false
# required: YES
# default: true
disable_publicKey = true

# When enabled, HonSSH will block any attempts to start an X11 session.
# You can allow X11 but HonSSH will not log the session.
#
# input: true/false
# required: YES
# default: true
disable_x11 = true

# When enabled, HonSSH will block any attempts to start an SFTP session.
# HonSSH will log SFTP traffic and capture downloaded files.
#
# input: true/false
# required: YES
# default: false
disable_sftp = false

# When enabled, HonSSH will block any attempts to start an EXEC session.
# HonSSH will log all EXEC sessions, including SCP transfers.
#
# input: true/false
# required: YES
# default: false
disable_exec = false

# When enabled, HonSSH will block any attempts to start running port forwarding over SSH.
# You can allow port forwarding but HonSSH will not log the session - Yet! (log to PCAP?)
#
# input: true/false
# required: YES
# default: true
disable_port_forwarding = true

#-----------------------#
#   OUTPUT DIRECTORIES  #
#-----------------------#
[folders]

# Directory where log files will be saved in.
#
# input: Text
# required: YES
# default: logs
log_path = logs

# Directory where session files will be saved in.
#
# input: Text
# required: YES
# default: sessions
session_path = sessions

#-----------------------#
#  ADVANCED NETWORKING  #
#-----------------------#
[advNet]

# To enable this HonSSH must be ran as root or an account allowed to run 
# iptables and ip link/addr commands.
#
# With this disabled, the honeypot will always see connections coming from
# honey_addr. With this enabled, connections will look as if the connections
# are coming from the attacker.
# See the Wiki page for more details.
# https://code.google.com/p/honssh/wiki/AdvancedNetworking
#
# input: true/false
# required: YES
# default: false
enabled = false

#-----------------------# - DISABLED in this release - Awaiting improvements
#    LIVE INTERACTION   # - DISABLED in this release
#-----------------------# - DISABLED in this release
[interact]

# Session management interface.
#
# This is a telnet based service that can be used to interact with active
# sessions. Disabled by default.
#
# input: true/false
# required: YES
# default: false
# DISABLED in this release
enabled = false  

# Interface to create the interaction on - 0.0.0.0 for all.
#
# input: IP Address
# required: if interact_enabled = true
# default: 127.0.0.1
# DISABLED in this release
interface = 127.0.0.1

# Port to create the interaction on
#
# input: Number
# required: if interact_enabled = true
# default: 5123
# DISABLED in this release
port = 5123

#-----------------------#
#   PASSWORD SPOOFING   #
#-----------------------#
[spoof]

# Enabling this will allow HonSSH to spoof an incorrect password with the real password. 
# A list of users and passwords must be defined in the users.cfg file.
#
# Passwords to spoof can either be a fixed list or a random chance.
# 
# See the Wiki page for more details.
# https://code.google.com/p/honssh/wiki/PasswordSpoofing
#
# input: true/false
# required: YES
# default: false
enabled = false

# Location of the users.cfg file
#
# input: text
# required: if enabled is true
# default: users.cfg
users_conf = users.cfg

#----------------------------------------------#
#              LOGGING AND OUTPUTS             #
#----------------------------------------------#

#-----------------------#
#      TEXT LOGGING     #
#-----------------------#
[txtlog]

# All activity will be logged to text files
# A log of entry attempts will be kept in log_path/
# A log of session activity will be kept in session_path/
#
# input: true/false
# required: YES
# default: true
enabled = true

#-----------------------#
#      MYSQL LOGGING    #
#-----------------------#
[database_mysql]

# All activity will be logged to a MYSQL Database
# Database structure for this module is supplied in doc/sql/mysql.sql
#
# input: true/false
# required: yes
# default: false
enabled = false

# IP address of the database
#
# input: IP Address
# required: if enabled = true
# default: localhost
host = localhost

# Port to connect to the database on
#
# input: Number
# required: NO
# default: 3306
port = 3306

# Name of the database
#
# input: Text
# required: if enabled = true
database = dockpotdatabase

# Username to authenticate with the database
#
# input: Text
# required: if enabled = true
username = username

# Password to authenticate with the database
#
# input: Text
# required: if enabled = true
password = password

#-----------------------#
#      EMAIL LOGGING    #
#-----------------------#
[email]

# Send an email upon hacker connect
#
# dependency: txtlog MUST be enabled
# input: true/false
# required: YES
# default: false
login = false

# Send an email upon hacker disconnect - Will attach the tty log file
#
# dependency: txtlog MUST be enabled
# input: true/false
# required: YES
# default: false
attack = false

# Your SMTP Host
#
# input: Text
# required: if login or attack = true
host = 

# Your SMTP Port
#
# input: Number
# required: if login or attack = true
port = 

# Use SSL/TLS to connect to the SMTP provider?
#
# input: true/false
# required: if login or attack = true
# default: true
use_tls = true

# Does your SMTP provider require a login?
#
# input: true/false
# required: if login or attack = true
# default: true
use_smtpauth = false

# Your SMTP login username
#
# input: Text
# required: if use_smtpauth = true
username =  

# Your SMTP login password
#
# input: Text
# required: if use_smtpauth = true
password = 

# The address the email is sent from
#
# input: Email Address
# required: if login or attack = true
from = 

# The address(es) the email is sent to
#
# input: Email Addresses in a comma seperated list without spaces
# required: if login or attack = true
to = 

#-----------------------#
#        HP FEEDS       #
#-----------------------#
[hpfeeds]

# All activity will be logged to a hpfeeds broker for dissemination 
# between the honeypot community. 
# Authentication attempts will be logged to honssh.auth
# Sessions will be logged to honssh.sessions
#
# input: true/false
# required: yes
# default: false
enabled = false

# The server address of the hpfeeds broker
#
# input: Text
# required: if enabled = true
server = 

# The server port of the hpfeeds broker
#
# input: Number
# required: if enabled = true
port = 

# Your hpfeed authe key identifier
#
# input: Text
# required: if enabled = true
identifier = 

# Your hpfeed authe key secret
#
# input: Text
# required: if enabled = true
secret = 

#-----------------------#
#    FILE DOWNLOADING   #
#-----------------------#
[download]

# File Download
#
# HonSSH wil attempt to download all scp and sftp files to a local store if this is true
#
# input: true/false
# required: YES
# default: false
passive = false

# HonSSH wil attempt to download all wget files to a local store.
# 
# I believe another tool should be used to passivley capture all http(s) connections on all ports - maybe the next project?
# Until then HonSSH will use a 'best effort' approach to capture files when the wget commands is detected.
# It will not be able to capture commands such as:
# url=www.test.url; wget $url
# 
# input: true/false
# required: YES
# default: false
active = false

#-----------------------#
#     PACKET LOGGING    #
#-----------------------#
[packets]

# Log all SSH Packets to text file (.log-adv)
#
# input: true/false
# required: YES
# default: false
enabled = false

#-----------------------#
#   APPLICATION HOOKS   #
#-----------------------#
[app_hooks]
# If you want any other application hooks or arguments passing, raise an issue
# on the HonSSH code page. 

# Calls the script when a connection is made with the following arguments
# ./script CONNECTION_MADE DATETIME IP PORT
#
# input: path of script to run
# required: NO
connection_made = 

# Calls the script when a connection is lost with the following arguments
# ./script CONNECTION_LOST DATETIME IP
#
# input: path of script to run
# required: NO
connection_lost = 

# Calls the script when a login is successful with the following arguments
# ./script LOGIN_SUCCESSFUL DATETIME IP USERNAME PASSWORD
#
# input: path of script to run
# required: NO
login_successful = 

# Calls the script when a login has failed with the following arguments
# ./script LOGIN_FAILED DATETIME IP USERNAME PASSWORD
#
# input: path of script to run
# required: NO
login_failed = 

# Calls the script when a command is entered with the following arguments
# ./script COMMAND_ENTERED DATETIME IP COMMAND
#
# input: path of script to run
# required: NO
command_entered = 

# Calls the script when a file download is started with the following arguments
# ./script DOWNLOAD_STARTED DATETIME IP LINK FILE_PATH
#
# input: path of script to run
# required: NO
download_started = 

# Calls the script when a file download is finished with the following arguments
# ./script DOWNLOAD_FININSHED DATETIME IP LINK FILE_PATH
#
# input: path of script to run
# required: NO
download_finished = 



[docker]


uri=unix://var/run/docker.sock
version=1.12
image_name=eg_sshd

**Comment by bang-uin** [comment]
Your config file looks not complete. 
What honssh version are you using? 
[honeypot-static] and [honeypot-docker] sections are missing. 
Probably even more.
Please use the latest version.

**Comment by bang-uin** [comment]
And please read our Wiki articles.

**Comment by jcbeaub** [comment]
@bang-uin 
As I stated in my initial post I am using the dockpot honeypot but it is heavily based upon honssh so I was here to mostly ask about the IP configuration as honssh says its running but I can’t ssh to it

**Comment by bang-uin** [comment]
I see, sorry, didn't saw it :D
But i highly recommend to first try the release 1.1.0 from our repo before investing more time in 3 years old code.
The dockpot project seems pretty much dead.

**Comment by jcbeaub** [comment]
@bang-uin I totally agree with you but unfortunately my college professor (who knows nothing about dockpot) has chosen dockpot as a high interaction honeypot that we must look into. As I said, any assistance or advice on setting up the honssh.cfg is greatly appreciated.

**Comment by tnich** [comment]
As @bang-uin said, we can't really comment on Dockpot setups but I'll explain a bit more about HonSSH that might help.

A traditional HonSSH setup would be setup like this - https://github.com/tnich/honssh/wiki/Deployment-Guide
ssh_addr is the address you want to bind your HonSSH server to. This is address that attackers will SSH into. ssh ssh_addr will connect to HonSSH. This should be an IP that exists on your HonSSH server or 0.0.0.0 to bind to every interface.

client_addr is the address that HonSSH will send outgoing connections from, destined to the honeypot.
Again, use 0.0.0.0 to use any interface.

honey_addr is the address of the honeypot that you want HonSSH to send the SSH packets to. Usually this is on the same subnet ad the client_addr (unless 0.0.0.0 is used).

We can do docker directly in the new HonSSH, no need for dockpot anymore.
https://github.com/tnich/honssh/wiki/Setup-using-Docker

I hope this helps :smile: Let us know if you need anything else!
