### ISSUE TITLE
Password Decoy Not working

### ISSUE THREAD

**Issue by rajasaad7** [tnich/honssh#123]
When I try to connect through fake password it spoof password but donot creates a session my honssh.cfg and user.cfg attached!
Kindly check what am I missing?

**user.cfg:**

[good]
real_password = saad
fake_passwords = daas, daas2, daas3

**honssh.cf:**

[Honssh.txt](https://github.com/tnich/honssh/files/2273130/Honssh.txt)

**Comment by tnich** [comment]
Hi,

Can you attach the honssh.log file too please?

Many thanks,
Tom

**Comment by rajasaad7** [comment]
**Honssh.log :**
2018-08-09T12:30:45+0500 [-] [PRE_AUTH] - CLIENT CONNECTED, REPLAYING BUFFERED PACKETS
2018-08-09T12:30:45+0500 [HonsshClientTransport,client] [SSH] - Detected Public Key Auth - Disabling!
2018-08-09T12:30:47+0500 [HonsshServerTransport,0,127.0.0.1] [SPOOF] - Real password match good/saad
2018-08-09T12:30:47+0500 [-] [POST_AUTH] - Details the same as pre-auth, not re-directing
2018-08-09T12:30:49+0500 [HonsshClientTransport,client] [SSH] - Detected Public Key Auth - Disabling!
2018-08-09T12:30:51+0500 [HonsshClientTransport,client] [SSH] - Detected Public Key Auth - Disabling!

**Comment by tnich** [comment]
Your honssh.cfg still shows "honey_ip = 127.0.0.1" - I  thought you changed
that in your other ticket?

**Comment by rajasaad7** [comment]
yess on other I can open my ssh session using original password but cant access through fake pass

**Comment by tnich** [comment]
What do you mean by "other"?

Also, can you share the entire honssh.log file? Feel free to email it
directly from my email address in the code.

**Comment by rajasaad7** [comment]
I can open ssh session on my machine with ssh kippo@127.0.0.1 -p 2222 with orignel pass of user i.e. 8520 but cant access though fake pass!

**Comment by tnich** [comment]
Is the username "good" defined on your machine? try changing [good] to
[kippo] then logging in with kippo:daas

**Comment by rajasaad7** [comment]
[log.txt](https://github.com/tnich/honssh/files/2273296/log.txt)

complete log file of local host

**Comment by rajasaad7** [comment]
2018-08-09T12:59:34+0500 [-] [PRE_AUTH] - CLIENT CONNECTED, REPLAYING BUFFERED PACKETS
2018-08-09T12:59:34+0500 [HonsshClientTransport,client] [SSH] - Detected Public Key Auth - Disabling!
2018-08-09T12:59:38+0500 [HonsshServerTransport,0,127.0.0.1] [SPOOF] - Fixed password match kippo/daas
2018-08-09T12:59:38+0500 [-] [POST_AUTH] - Details the same as pre-auth, not re-directing
2018-08-09T12:59:38+0500 [-] [POST_AUTH] - Spoofing Password
2018-08-09T12:59:40+0500 [HonsshClientTransport,client] [SSH] - Detected Public Key Auth - Disabling!
2018-08-09T12:59:42+0500 [HonsshClientTransport,client] [SSH] - Detected Public Key Auth - Disabling!
2018-08-09T12:59:42+0500 [HonsshServerTransport,0,127.0.0.1] [SPOOF] - Fixed password match kippo/daas
2018-08-09T12:59:42+0500 [-] [POST_AUTH] - Details the same as pre-auth, not re-directing
2018-08-09T12:59:42+0500 [-] [POST_AUTH] - Spoofing Password
2018-08-09T12:59:44+0500 [HonsshClientTransport,client] [SSH] - Detected Public Key Auth - Disabling!
2018-08-09T12:59:47+0500 [HonsshClientTransport,client] [SSH] - Detected Public Key Auth - Disabling!


Kippo:daas result after changing "good" with "kippo" in user.cfg

**Comment by rajasaad7** [comment]
Kippo saad works beause it is orignel password of kippo user!!
kippo daas is fake password that is provided in user.cfg...
it shows fixed password match kippo/daas but then Details the same as pre-auth, not re-directing
as in last message!

if attacker can only connect with orignel pass of user that this honeypot is only for logging commands I guess, I think it should provide a fake session so that what atttacker do in fake session could not affect real system? does it work that way or I am wrong?

**Comment by rajasaad7** [comment]
I think you are in a confusion that real_password = saad i.e working?
I cannot generate a session with real_password nor  with fake_passwords that are provided in user.cfg
by orignel pass I mean that is used to login in that machine when I power on my pc!!

**Comment by tnich** [comment]
It does not provide a fake session. All sessions on HonSSH are real and the
attack can do whatever they want as far as HonSSH in concerned.

HonSSH is not meant to be run on one server like you are doing
(honey_ip:127.0.0.1). It is meant to be run on multiple servers, one for
HonSSH and one honeypot.

If you want something that does fake sessions, you should look at
https://github.com/micheloosterhof/cowrie

**Comment by rajasaad7** [comment]
so how does that password Spoofing work!
It gives session with fakepassword and attacker thinks that this is the right password?
also you are telling that kippo(honeypot) and honssh should be on different machines? 
cant they be on same machine?

**Comment by tnich** [comment]
"It gives session with fakepassword and attacker thinks that this is the
right password?" - Yes.

They should be on different machines as per -
https://github.com/tnich/honssh/wiki/Deployment-Guide#scenario-two

Once the attacker gets access to the honey pot, they can do whatever they
want - including killing the HonSSH process. So it would be a bit pointless
to put them on the same machine.

**Comment by rajasaad7** [comment]
okay! Now see this Secanrio!
machine ip is 115.186.176.142
honeypot(kippo) is running on same machine at port 5001
honssh is running on port 22

**Honssh.cfg:**
[Honsscfg.txt](https://github.com/tnich/honssh/files/2273461/Honsscfg.txt)

**User.cfg:**
[decoy]
real_password = toor
fake_passwords = fakepass
**Complete Log file:**
[log.txt](https://github.com/tnich/honssh/files/2273476/log.txt)

It Could not connect with ssh decoy@115.186.176.142 -p 22 not with toor nor with fakepass
what shoud I do to get session with these pass? 
Thanks for Replying on Time I appericate your help <3

**Comment by tnich** [comment]
Do you have "decoy" defined as a user on the machine?

Also, you still have "honey_ip = 127.0.0.1", which means HonSSH and the
honeypot are running on the same machine.

You keep referring to "kippo", this is not Kippo. If you are after
something like Kippo, then as before, I would use cowrie.

This guide may also help if you want to progress with HonSSH:
https://www.robertputt.co.uk/learn-from-your-attackers-ssh-honeypot.html

**Comment by rajasaad7** [comment]
Sir! Firstly I would thank you for being here.

No I don't have decoy defined on user machine!

If they are running on same machine it should provided a session with fakepassword or realpassword as it provides with original password of root.

kippo is to honeypot i am refering to!
according to me I think honssh works as a proxy between kippo and attacker? am I right?

**Comment by rajasaad7** [comment]
okay now lets see this : 
honnssh = 115.186.176.142
honeypot = 115.186.176.141
username defined on honeypot machine is decoy
**honssh.cfg**
[honsshcfg.txt](https://github.com/tnich/honssh/files/2273837/honsshcfg.txt)

**honssh.log**
[logs.txt](https://github.com/tnich/honssh/files/2273848/logs.txt)

**user.cfg**
[decoy]
real_password = toor
fake_passwords = fakepass

**Comment by tnich** [comment]
From this configuration, the HonSSH machine (115.186.176.142) should be
able to SSH to the honeypot like this:
ssh decoy@115.186.176.141
Using a password or toor

If this does not work, then the fake password will not work.

I have just tried from my laptop and cannot get in with decoy:toor

**Comment by rajasaad7** [comment]
sorry my bad.. it is real_password = saad

**Comment by tnich** [comment]
Still doesn't work:
$ ssh -p 5001 decoy@115.186.176.141
decoy@115.186.176.141's password:
Permission denied, please try again.

**Comment by rajasaad7** [comment]
user.cfg update with new user created:
[scene]
real_password = wud1991@WUD
fake_passwords = fakepass
this is working fine for me..
root@itsec:/home/itsec/honssh# ssh scene@115.186.176.141 -p 5001
key_load_public: invalid format
scene@115.186.176.141's password: 
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-131-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 updates are security updates.

Last login: Thu Aug  9 16:01:36 2018 from 39.41.244.17
scene@scene:~$

**Comment by tnich** [comment]
Good, and HonSSH is working as expected too.

**Comment by rajasaad7** [comment]
now when I ssh 115.186.176.142 -p 22 where honssh is running as an attacker what pass shoud I give to login? fakepass (i.e. is not working)

**Comment by tnich** [comment]
ssh scene@115.186.176.142 with a password of fakepass works fine for me
when testing from here.

**Comment by rajasaad7** [comment]
okay Thanks for The Help Sir! you are amazing <3

**Comment by tnich** [comment]
Glad it's working.

I have to say that this setup is not ideal. You have publicly given out the
login details to the real server (115.186.176.141) and told everyone that
this is a honeypot.

The best deployment for HonSSH is for the honeypot server to be sitting
behind the HonSSH server.

If this is all for testing, then it's fine to play around with. Just please
be aware of the security considerations.
