### ISSUE TITLE
Double calls/Double logs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tnich/honssh#53]
```
When I check the log of the server I find it logging twice, also the functions 
are called twice

when I use ipdb to debug the code I find that it brings me back to the same 
line when I tell it to continue 


I can't figure it out

Help appreciated 


```

Original issue reported on code.google.com by `3ABED.FCI@gmail.com` on 10 Feb 2015 at 12:23

**Comment by tnich** [comment]
Running HonSSH with:

    twistd -y honssh.tac -n

Will create duplicate logging to stout, however HonSSH still appears to work correctly behind the scenes. 

Cannot reproduce the multiple function calling.
