### ISSUE TITLE
Password Spoofing Not Working

### ISSUE THREAD

**Issue by lazyboyswag** [tnich/honssh#60]
So I have set the password spoofing capability to a 50% random chance, but when I try to ssh into the honeypot using Kali I could never get in.  Would anyone know what my problem may be??

**Comment by tnich** [comment]
Hey,

Please ensure the password spoofing option is enabled and your users.cfg is correct too (correct real password etc).

If they all look good, attach your honssh.log and configuration files here and I'll take a look.

**Comment by lazyboyswag** [comment]
I checked my logs and it turns out that the SSH connection times out after 10 seconds from when an attacker attempts to ssh into my honssh box.  Could there something wrong with my configuration???  Posting logs and config files shortly

**Comment by lazyboyswag** [comment]
I am sending you my honssh.cfg; users.cfg; and my honssh.log files

**Comment by lazyboyswag** [comment]
![screenshot 24](https://cloud.githubusercontent.com/assets/14087460/9637808/1cf5b590-5160-11e5-8d08-f88525f771d2.png)
![screenshot 25](https://cloud.githubusercontent.com/assets/14087460/9637812/236f07b4-5160-11e5-88bf-a6a05726aa09.png)
![honsshloggy](https://cloud.githubusercontent.com/assets/14087460/9637820/288b564e-5160-11e5-8ca6-37d4ce9c2abb.JPG)

**Comment by lazyboyswag** [comment]
I am using Ubuntu 14.04 for honssh I just took the pictures in of the files on my windows machine

**Comment by tnich** [comment]
Looks like an issue with your setup and the "Advanced  Networking" feature. Can you try disabling the AdvNet in the conf file.

For advanced networking to work, honssh needs to be the default gateway for the honeypot.

**Comment by lazyboyswag** [comment]
I disabled the AdvNet section in the conf file but now i get two new
errors.  The first error says that table "HonSSH.auth doesn't exist".  The
second error is "Detected Public Key Auth - Disable"

**Comment by lazyboyswag** [comment]
I have fixed the first problem, it was configured wrong, but for the second error "Detected Public Key Auth - Disabling!" I have no idea how to fix that problem.  Any suggestions???

**Comment by lazyboyswag** [comment]
![honsshbasic](https://cloud.githubusercontent.com/assets/14087460/9649404/ace0c180-51b1-11e5-92c9-39c53ddcc883.JPG)

**Comment by tnich** [comment]
See the comment on Issue #61
