### ISSUE TITLE
"Detected Public Key Auth - Disabling" Error

### ISSUE THREAD

**Issue by lazyboyswag** [tnich/honssh#61]
I have starting HonSSH in the background and its starts working, but the moment I try to SSH into it (I enabled password spoofing) from my Kali Linux box i get an error with Public Key Disabling.  I thought HonSSH does not work with public keys.
![honsshbasic](https://cloud.githubusercontent.com/assets/14087460/9650669/952392b8-51c3-11e5-98ff-be46af026e8f.JPG)

**Comment by tyrel227** [comment]
I am having the same problem with Public Key Auth, are we suppose to allow it in HonSSH.cfg file?

**Comment by tnich** [comment]
Hi,

Public key auth does not work with honssh. It is advised to keep public key disabled in the conf file.

That message is purely informational. It means the attacker attempted to auth with public key, and honssh rejected it.

**Comment by lazyboyswag** [comment]
Does that mean HonSSH is functioning properly???

**Comment by tnich** [comment]
Yep. Can you connect and does it generate logs?

**Comment by lazyboyswag** [comment]
I can't sign in with a password, but it does generate logs for the incorrect passwords I input.

**Comment by tnich** [comment]
Can you SSH normally into the honeypot? ssh honey_addr:honey_port and login with the users and real_passwords of users.cfg 

Feel free to email me and logs, topology diagrams etc to thomas@honeynetproject.se

**Comment by lazyboyswag** [comment]
I have sent two emails to you: one containing the users and honnsh configuration files; and the other contain log files.  I very much appreciate the help you are giving.
