### ISSUE TITLE
issue with honsshctrl.sh when generating keys.

### ISSUE THREAD

**Issue by mchaos** [tnich/honssh#68]
I upgraded honssh recently. I have been running the same version for almost a year and saw that there was some good updates and I wanted to check out honsshinteraction.py

When I went to run honssh for the first time I received an error where it does not find generated keys and attempts to generate them and I get "ERROR: option --no-passphrase not recognized"

then displays the options for ckeygen,

then obviously honssh fails to start. It does this for both keys.

I am able to remedy the issue by editing the honsshctrl.sh script and removing the --no-passphrase option. I made sure I had the newest version of twisted-conch, which it is.

The funny thing is it does not list --no-passphrase in the options as it fails... This is being run on a raspberry pi. On my laptop when I install python-twisted-conch I get the --no-passphrase option.

Not sure if this issue is with the reps for raspian however I do see an issue for most setting up honssh on pi's.

**Comment by tnich** [comment]
Hey,

Yeah, sorry the --no-passphrase option is only available in newer releases of Twisted and the raspbian repos still have an older one.

You can manually update twisted with pip:
pip install twisted --upgrade

and this should fix the issue.

Let me know if it works.

**Comment by Bifrozt** [comment]
I'll update `honsshctrl.sh` to catch this issue.

**Comment by Bifrozt** [comment]
@mchaos
When you have time, can you please provide me with
- operating system info (`lsb_release -a`)
- current version of Twisted (`python -c "import twisted; print twisted.__version__"`)

**Comment by mchaos** [comment]
I will try it. It will be later because I am out and about.

Yours Truly,
Donald S. Reiman

**Comment by mchaos** [comment]
I updated twisted via pip and it's not showing the --no-passphrase option.
I'll give honssh a fresh go to see if it's just not telling me it's there.

Yours Truly,
Donald S. Reiman

**Comment by mchaos** [comment]
No go. Upgrading with pip aparantly has still left me with the old ver.

Removing the --no-passphrase from the script gets it going.

Yours Truly,
Donald S. Reiman

**Comment by tnich** [comment]
What Twisted version are you at now after the pip upgrade?

python
import twisted
print twisted.version

**Comment by mchaos** [comment]
Twisted version: 13.2.0

**Comment by mchaos** [comment]
Twisted version: 13.2.0

Distributor ID: Ubuntu
Description: Ubuntu 14.04.3 LTS
Release: 14.04
Codename: trusty

**Comment by tnich** [comment]
Hmm, when I run the pip upgrade, it updates me to 15.2.1:

root@xxx ~ # pip install twisted --upgrade
Downloading/unpacking twisted from https://pypi.python.org/packages/source/T/Twisted/Twisted-15.5.0.tar.bz2#md5=0831d7c90d0020062de0f7287530a285
  Downloading Twisted-15.5.0.tar.bz2 (3.1Mb): 3.1Mb downloaded

Are you sure the pip command finished successfully?

**Comment by mchaos** [comment]
I'll give it a shot. I will cut paste from your message to make sure.

**Comment by mchaos** [comment]
Not sure what I did wrong, but now it is downloading 15xx and installing.

I was updationg via my android in the passenger seat of the car while
traveling so.... :p

**Comment by mchaos** [comment]
that is very weird, it now says I am running twisted 12xx

Let me reboot

**Comment by mchaos** [comment]
heres the issue. I am getting an error. I'll see if I can fix it.

 Running setup.py egg_info for package twisted
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown
distribution option: 'install_requires'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown
distribution option: 'extras_require'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown
distribution option: 'zip_safe'
      warnings.warn(msg)
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown
distribution option: 'include_package_data'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: invalid command 'egg_info'
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown
distribution option: 'install_requires'

  warnings.warn(msg)

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution
option: 'extras_require'

  warnings.warn(msg)

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution
option: 'zip_safe'

  warnings.warn(msg)

/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution
option: 'include_package_data'

  warnings.warn(msg)

usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

   or: -c --help [cmd1 cmd2 ...]

   or: -c --help-commands

   or: -c cmd --help



error: invalid command 'egg_info'

**Comment by tnich** [comment]
Try: pip install --upgrade setuptools

**Comment by mchaos** [comment]
no dice

**Comment by mchaos** [comment]
okay, so I downloaded and installed twisted 15.5.0 manually. Confirmed that
I am running twisted 15.5.0 however I still do not see the --no-passphrase
option.

**Comment by mchaos** [comment]
Okay, now when I check the version I see 15.5.0 but when I run ckeygen
--version I get twisted version 12.0.0

Okay, now I am confused....
