### ISSUE TITLE
Honsshcrt.sh clean

### ISSUE THREAD

**Issue by Mil0n** [tnich/honssh#76]
How to resolve this error
An error has occurred: 'Couldn't listen on 192.168.1.5:22: [Errno 98] Address already in use.'
Please look at log file for more information.

**Comment by Bifrozt** [comment]
Hi,

The reason for this is that something refuses to give up it's claim to tcp/22.

Can you please reproduce the issue but, use bash -x honsshctrl.sh clean, and paste the output here?

**Comment by Mil0n** [comment]
I restarted the server and is working just fine now.

Thanks
