### ISSUE TITLE
Automate HonSSH

### ISSUE THREAD

**Issue by Mil0n** [tnich/honssh#77]
Hi all,

There way to write a script to guide administrators in the installation of Honssh.

Thanks

**Comment by Bifrozt** [comment]
Is it something like this you are thinking of?
http://bifrozt.github.io/bifrozt-ansible/

**Comment by Mil0n** [comment]
No but a script to install the honssh after downloading from github.

**Comment by tnich** [comment]
What exactly are you wanting to achieve? You don't need to install honssh, just configure and run

**Comment by Bifrozt** [comment]
Okay, so you need a script that downloads and configures HonSSH but
- don't configure a DHCP server on the internal network
- don't configures network on eth1
- don't add any firewall rules
- don't prevent outbound attacks
- don't configure any firewall logging

If this is correct, i think @tnich covered all the steps needed in a script.

**Comment by robputt796** [comment]
+1 vote for using the Ansible playbook here... totally makes sense. You can see here that it pulls the HonSSH to configure from Github - https://github.com/Bifrozt/bifrozt-ansible/blob/master/roles/honssh/tasks/main.yml#L3

**Comment by Mil0n** [comment]
Thank you all. Bifrozt-Ansible works.
