### ISSUE TITLE
Versioned Releases?

### ISSUE THREAD

**Issue by robputt796** [tnich/honssh#78]
Hi @tnich @Bifrozt 

What are your thoughts on doing tagged versioned releases of HonSSH?

All the best,

Rob

**Comment by Bifrozt** [comment]
Is this what you are thinking about?
https://git-scm.com/book/en/v2/Git-Basics-Tagging

I've never used tags, nor did i knew they existed, :+1: for that info :)
Apart from what's described on the Tagging page, how would you suggest to use them?

**Comment by robputt796** [comment]
Yep thats exactly what I am thinking of.

Essentially I've seen a few issues raised now with users trying to implement a HonSSH Honey Pot, my anticipation is using this we can create tagged stable versioned released rather than people constantly installing the master branch, and then a set of guides can be created covering the installation for each tagged version. Hopefully this would cut down on the number of issues from honey pot operators struggling to get the cutting edge branch up and running.

**Comment by Bifrozt** [comment]
So using tags instead of branches or as a compliment to branches?

**Comment by robputt796** [comment]
As a compliment, typically development of new features would be completed on branches or forks, and then merged into master once the reviewer is happy with the PR, and then following this when master has been tested and verified as working and stable it will be assigned a version tag to indicate a stable release. Not every merge to master needs to become a tagged release though.

**Comment by bang-uin** [comment]
We will now use the git flow approach and new releases will get tagged.

Therefore closing this.

Thanks.
