### ISSUE TITLE
Functionality request

### ISSUE THREAD

**Issue by rbtux** [tnich/honssh#79]
Functionality request.
Call a script/executable when the client disconnect from server.

**Comment by tnich** [comment]
Hi rbtux,

This functionality already exists in the "Application Hooks" section of the config file. Simply enable it and point it to a script.

Let me know if you need any help or would like any additional arguments passing to it.

`#-----------------------#
#   APPLICATION HOOKS   #
#-----------------------#
[output-app_hooks]

# Enable app_hooks output plugin
#
# input: true/false
# required: YES
# default: false
enabled = true

# Calls the script when a connection is lost with the following arguments
# ./script CONNECTION_LOST DATETIME IP PORT HONEYIP HONEYPORT SESSION_ID
#
# input: path of script to run
# required: NO
connection_lost = /script/to/call.sh`

**Comment by rbtux** [comment]
ha ha... i feel stupid now. i was misreading the conf file!
