### ISSUE TITLE
Prevent abuse of the honeypot machine

### ISSUE THREAD

**Issue by unixfox** [tnich/honssh#83]
Actually the honeypot machine isn't protected against high bad misuses like:
- Be a part of a botnet (semi protected because it closes the Docker container after exiting the SSH session)
- Launching DDOS attacks
- Launching a forkbomb or consuming larger resources
- ...

I did have a look at @Bifrozt's work (https://github.com/Bifrozt/bifrozt-ansible) that include a protection but it doesn't support Docker. So maybe integrate the protections of the bifrozt ansible playbook inside HonSSH or create a documentation page to explain how to protect the honeypot (that include an automated script?) ?

**Comment by tnich** [comment]
Yeah, I think I've just assumed users would be clever enough to sort the protection out themselves. I don't really want to evolve HonSSH into anything more than a SSH proxier, I think other projects (like @Bifrozt) should add those sort of things.

The iptables rules in @Bifrozt are what I usually use:
https://github.com/Bifrozt/bifrozt-ansible/blob/master/roles/network/templates/etc/network/ipv4hater

**Comment by unixfox** [comment]
Okay I think I'll make a wiki page for that with any information I found to protect the honeypot.

**Comment by tnich** [comment]
Sounds good, thanks a lot :smile:

**Comment by Bifrozt** [comment]
Honeypots will always be subject to abuse (working as intended ;) ) but, there's a level of risk that should be addressed when it comes to deploying them.

These docs will provide a bit more info regarding risks/abuse in the context of honeypots
- https://github.com/Bifrozt/bifrozt-ansible/wiki/Risks.
- http://old.honeynet.org/papers/honeynet/
