### ISSUE TITLE
Asciinema support

### ISSUE THREAD

**Issue by unixfox** [tnich/honssh#84]
As honssh supports [Cowrie](https://github.com/micheloosterhof/cowrie) (kippo fork) we could integrate [Asciinema](https://github.com/micheloosterhof/cowrie/blob/master/bin/asciinema) inside the honssh repo ?

**Comment by unixfox** [comment]
I can confirm that it's working great ! Proof: https://asciinema.org/a/e19rwv2t79uu81u76f1wv8i3c

**Comment by unixfox** [comment]
@tnich Do you know if it's allowed in the license of Cowrie to integrate their tool inside the repo of Honssh ?

**Comment by tnich** [comment]
@unifox - I will need to look into this before integrating it in.

**Comment by tnich** [comment]
Added 😄
