### ISSUE TITLE
Error at "Unable to find id_dsa, generating it now"

### ISSUE THREAD

**Issue by unixfox** [tnich/honssh#85]
I did a fresh reinstall of my OS (Debian 8) and I reinstalled all of python requirements using pip but I'm getting an new error that I've never seen before when I launching honSSH:

```
honsshctrl.sh[19047]: WARNING: Unable to find id_dsa, generating it now...
Generating public/private dsa key pair.
Traceback (most recent call last):
  File "/usr/local/bin/ckeygen", line 11, in <module>
    load_entry_point('Twisted==16.5.0', 'console_scripts', 'ckeygen')()
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/scripts/ckeygen.py", line 64, in run
    generateDSAkey(options)
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/scripts/ckeygen.py", line 121, in generateDSAkey
    backed=default_backend(),
TypeError: generate_private_key() got an unexpected keyword argument 'backed'
```

My config file: http://pastebin.com/vgfnVpKP

The error is maybe related to the newer version, I think generating the DSA key was working great on older version of Twisted (14.0).

I'll try tomorrow if using the debian package: `python-twisted` it can work.

**Comment by bang-uin** [comment]
Yes, it is a problem with the newest twisted package. There is a typo "backed" instead of "backend" at File "/usr/local/lib/python2.7/dist-packages/twisted/conch/scripts/ckeygen.py", line 121.
Manually fixing the typo fixes the key generation.

**Comment by unixfox** [comment]
Thank you @bang-uin I just pull a request on the twisted repository: https://github.com/twisted/twisted/pull/582

**Comment by unixfox** [comment]
Will be fixed in the next release of twisted: https://github.com/twisted/twisted/pull/569/files#diff-4c29d4ad8175eadfb16c7e219bc3f6fbR139

**Comment by tnich** [comment]
:+1:
